### ISSUE TITLE
complicated access for some Korp corpora

### ISSUE THREAD

**Issue by kreetrapper** [clarin-eric/resource-families-issues#384] opened 2021-07-14 17:20 UTC
Some corpora, at least **ParFin 2016**, **ParRus 2016**, and **Aleksis Kivi Corpus**, have a somewhat complicated access model. When clicking on the "Browse" links in the list of literary corpora you get a message in Finnish saying you need to login. When logging in, you still need to fill in an access request, including giving a reason why you want to access the corpus.

I suggest to add some additional information to the description/notes for these corpora to explain this behaviour a bit beforehand to make it easier for the casual user to actually access the corpus.

I don't know Korp well, maybe there's also a possibility to modify the link to force the interface to be English. Then just modifying the link thusly would be enough to smooth out the user experience.

**Comment by mmatthiesencsc** [comment] 2021-09-17 11:29
Hello,
The model is complicated because we can't know what access rights you have before you log in. First, to avoid the message in Finnish, you can change the UI language to English or Swedish. It then says:

You are trying to select or access corpora (or subcorpora) that require logging in to Korp and personal access rights.
Please log in to Korp to use the corpora if you have access rights to them.
If you do not have access rights to the corpora, please apply for them:

So you indeed need to fill out the application and have it approved. I would argue that this process relatively straight forward?
Maybe we could add a link to https://www.kielipankki.fi/access/ to explain the process?

**Comment by mmatthiesencsc** [comment] 2024-12-09 08:21
What are the criteria to close this one?

**Comment by lennes** [comment] 2024-12-12 14:30
I think FIN-CLARIN / The Language Bank of Finland cannot do much more to fix this issue, since the login procedure is  technically the same for all, and, like @mmatthiesencsc said, only after login can we know if the user needs to apply for access (in which case the user is redirected to the Language Bank Righst system) or if they already have access rights. The same process is offered directly via the Korp platform if the user lands on a corpus selection that is not publicly available. So, we cannot update it for individual resources in Korp or elsewhere.

Of course, the Resource Family listing is rather compact and no further details about individual access methods are offered there. The blue link only points to the "Concordancer" in this case and the license information is currently not completely shown (which is due to the old metadata profile offered via META-SHARE that does not provide sufficient options for describing and linking to the resource-specific license). Similarly, on VLO, our old "access location" link does not have any semantics, but it is currently only shown as a mysterious "URL", and the user cannot expect the login and application process. We will be able to address this when updating our CMDI profiles for VLO. In any case, at present, we think the process just works as intended, and we will try to make things more usable as we go along.

@jakoble, who can decide if/when this issue can be closed? If it cannot yet be closed, who defines the criteria (definition of done)?

**Comment by jakoble** [comment] 2024-12-12 14:37
I understand now & thanks for the explanation, so I'm closing the issue.

**Closed as completed by jakoble** 2024-12-12 14:37 UTC
Labels: FIN-CLARIN, literary corpora
